name: tests

on:
  push:
  pull_request:

jobs:
  build:
    name: ${{matrix.os}} - C++${{matrix.cppstd}}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # Ubuntu uses GCC, macOS uses Clang, Windows uses MSVC
        os: [ubuntu-latest, macos-latest, windows-latest]
        cppstd: [11, 14, 17, 20, 23]

    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: |
          cmake -S . -B build -DCMAKE_CXX_STANDARD=${{ matrix.cppstd }} -DCMAKE_BUILD_TYPE=Debug -DCMAKE_VERBOSE_MAKEFILE=ON -DTASK_THREAD_POOL_TEST=ON -DTASK_THREAD_POOL_TEST_COVERAGE=ON -DTASK_THREAD_POOL_BENCH=ON
          cmake --build build --config Debug

      - name: Test
        run: |
          cd build/tests
          ctest -C Debug --output-on-failure --verbose

      - name: Upload Coverage to Codecov
        if: contains(matrix.os, 'ubuntu')
        uses: codecov/codecov-action@v3
        with:
          gcov: true
          gcov_include: include/*
